version: "3.1"

services:
  parent-instance-client:
    image: tearust/parent-instance-client:nitro
    container_name: client
    network_mode: host
    volumes:
      - .log:/log
      - .tokenstate:/tokenstate
      - .libp2p:/libp2p
      - .layer1:/layer1
      - ./genesis.json:/tearust/data/genesis.json
      - .nitro:/nitro
    environment:
      ENCLAVE_CID: 6
      NITRO_PROXY_PORT: 8001
      AWS_REGION: ${AWS_REGION}
      NITRO_KEY_ID: ${NITRO_KEY_ID}
      LOG_FILE: /log/output.log
      NITRO_KEYS_PATH: /nitro/key
      GENESIS_CONFIG_PATH: /tearust/data/genesis.json
      LAYER1_WS_PROVIDER_URL: ${LAYER1_WS_PROVIDER_URL}
      LAYER1_KEY_PATH: /layer1/key
      INIT_LAYER1_KEY: ${INIT_LAYER1_KEY}
      LASTEST_TOPUP_HEIGHT: 8313477
      TEA_ID: "${TEA_ID}"
      MACHINE_OWNER: "${MACHINE_OWNER}"
      LIBP2P_NODE_KEY_PATH: /libp2p/key
      LIBP2P_BOOTNODES: ${LIBP2P_BOOTNODES}
      LIBP2P_ENABLE_RELAY_PEERS: "true"
      LIBP2P_SUPPORTED_PROTOCOLS: tea-0.14
      LIBP2P_AGENT_PROTOCOL: tea-0.14
      LIBP2P_VERSION: 0.14
      STATE_MAGIC_NUMBER: 200
      APPLY_VALIDATOR: "true"
      PERSIST_PATH: /tokenstate/persist
      RUST_BACKTRACE: full
      MALLOC_CONF: prof:true
    logging:
      driver: json-file
      options:
        max-size: 20m
        max-file: 5
