version: "3.1"

services:
  parent-instance-client:
    image: tearust/parent-instance-client:nitro
    container_name: client
    network_mode: host
    volumes:
      - .log:/log
      - .tokenstate:/tokenstate
      - .libp2p:/libp2p
      - .layer1:/layer1
      - ./genesis.json:/tearust/data/genesis.json
    environment:
      ENCLAVE_CID: 6
      LOG_FILE: /log/output.log
      GENESIS_CONFIG_PATH: /tearust/data/genesis.json
      # LAYER1_WS_PROVIDER_URL: ${LAYER1_WS_PROVIDER_URL}
      # LAYER1_KEY_PATH: /layer1/key
      TEA_ID: "${TEA_ID}"
      MACHINE_OWNER: "${MACHINE_OWNER}"
      LIBP2P_NODE_KEY_PATH: /libp2p/key
      LIBP2P_VERSION: "local0.1"
      IP_ADDRESS: ${IP_ADDRESS}
      LIBP2P_BOOTNODES: ${LIBP2P_BOOTNODES}
      # APPLY_VALIDATOR: "true"
      STATE_MAGIC_NUMBER: 100
      PERSIST_PATH: /tokenstate/persist
      RUST_BACKTRACE: full
