version: "3.1"

services:
  ##################    Layer1   #######################
  layer1:
    image: realraindust/tea-camellia:epoch6-0.1
    container_name: layer1
    volumes:
      - .layer1:/root/.local
    command: bash -c "tea-camellia 
                      --chain local 
                      --alice
                      --ws-max-connections 10000 
                      --unsafe-ws-external 
                      --unsafe-rpc-external 
                      --rpc-methods Unsafe 
                      --rpc-cors all 
                      --bootnodes /ip4/3.35.165.240/tcp/30333/p2p/12D3KooWNuASv6aVoqpM8j42yps76Ru6fYVWrkoJwyG4tbYcJngB"
    network_mode: host

  #####################   IPFS     #####################

  ipfs:
    image: ipfs/go-ipfs:v0.8.0
    container_name: ipfs
    volumes:
      - ".ipfs:/data/ipfs"
    network_mode: host

  # ################ Adapter  ##############

  adapter:
    image: realraindust/adapter:latest
    container_name: adapter
    network_mode: host
    environment:
      IPFS_PORT: 5001
      IPFS_SERVER: localhost
      RPC_CLIENTURL: http://localhost:5010
      WAIT_HOSTS: localhost:5001
      WAIT_TIMEOUT: 300
      WAIT_SLEEP_INTERVAL: 5

  # ################ Vmh-server  ##############

  vmh-server:
    image: realraindust/vmh-server:latest
    container_name: vmh
    network_mode: host
    environment:
      CLIENT_HOST: localhost

  parent-instance-client:
    image: realraindust/parent-instance-client:latest
    container_name: client
    network_mode: host
    volumes:
      - .log:/log
    environment:
      ADAPTER_CLIENT_URL: http://localhost:5011
      LAYER1_CLIENT_URL: http://localhost:5013
      LOG_FILE: /log/output.log
      VMH_HOST: localhost
      IPFS_HOST: localhost
      IPFS_PORT: 5001
      TEA_ID: 3zjLTxJHkEHI6NI4EJ7yoVCwF/OCIG4k/uky5jfC23s=
      TEA_ENV_SETTINGS:
        MODE:DEV
        PUBLIC_URLS:https://tearust.com
        FLUENCER_HTTP_MODE:leader-only
      JOIN_DEFAULT_RAFT_NETWORK: "false"
      LAYER1_NODE_IP: localhost
      LAYER1_NODE_PORT: 9944
      LAYER1_ACCOUNT: //Alice
      ORBITDB_IP: 139.198.14.205
      ORBITDB_PORT: 6001
      WAIT_HOSTS: localhost:5007, localhost:8000, localhost:5001, localhost:9944
      WAIT_TIMEOUT: 300
      WAIT_SLEEP_INTERVAL: 5
    entrypoint: /bin/bash
    stdin_open: true # docker run -i
    tty: true        # docker run -t
