version: "3.1"

services:
  parent-instance-client:
    image: tearust/parent-instance-client:nitro
    container_name: client
    network_mode: host
    volumes:
      - .log:/log
      - .tokenstate:/tokenstate
      - .libp2p:/libp2p
      - .layer1:/layer1
      - ./genesis.json:/tearust/data/genesis.json
    environment:
      ENCLAVE_CID: 6
      LOG_FILE: /log/output.log
      GENESIS_CONFIG_PATH: /tearust/data/genesis.json
      LAYER1_WS_PROVIDER_URL: wss://goerli.infura.io/ws/v3/4926c6c0569842b89fb5df97a537e198
      LAYER1_KEY_PATH: /layer1/key
      TEA_ID: "0xdf38cb4f12479041c8e8d238109ef2a150b017f382206e24fee932e637c2db7b"
      MACHINE_OWNER: 0x754d7b24d8a4ec00000000000000000000000000
      LIBP2P_NODE_KEY_PATH: /libp2p/key
      LIBP2P_VERSION: "local0.1"
      IP_ADDRESS: 127.0.0.1
      APPLY_VALIDATOR: "true"
      STATE_MAGIC_NUMBER: 100
      PERSIST_PATH: /tokenstate/persist
      RUST_BACKTRACE: full
    entrypoint: /bin/bash
    stdin_open: true # docker run -i
    tty: true # docker run -t
